services:
    strapi_database:
        container_name: strapi_database
        image: postgres:11
        environment:
            POSTGRES_PASSWORD: $DATABASE_PASSWORD
            POSTGRES_USER: $DATABASE_USERNAME
            POSTGRES_DB: $DATABASE_NAME
        ports:
            - $DATABASE_PORT:5432
        networks:
            strapi_backend:

networks:
    strapi_backend:
